### ISSUE TITLE
Enable heatmap over complete application

### ISSUE THREAD

**Issue by Cannonb4ll** [BrockReece/vue-heatmapjs#12]
I want to use your package in my application, but I have several components spreaded without having them in 1 App.vue file, my code in my HTML file (blade, laravel):

```
<div id="app">

    @include('components.topnav')

    <main>@yield('content')</main>

    @include('partials.footer')

    @auth
    <div id="user-sidebar" class="css3sidebar sidebar-right">
        <div class="c-user-sidebar__menu-wrapper menu-wrapper">
            @include('components.user-sidebar')
        </div>
    </div>
    @endauth
</div>
```

I am starting vue like this:

```
const app = new Vue({
    el: '#app',
});
```

I have tried adding v-heatmap to the <div id="app"> element but thats not working. How can I solve this?

**Comment by BrockReece** [comment]
Ah ok, I see the issue.
Maybe we could add an option to the directive to attach a heatmap to a specific element, '#app' in your example?
