### ISSUE TITLE
Use .npmignore

### ISSUE THREAD

**Issue by Shinigami92** [BrockReece/vue-heatmapjs#22]
Please use `.npmignore` so that you do not upload your entire repo to the `node_modules` folder

![Bildschirmfoto 2020-02-07 um 15 15 23](https://user-images.githubusercontent.com/7195563/74036521-b81fea00-49bc-11ea-9124-4bb812498ff8.png)

**Comment by BrockReece** [comment]
Sure, will look into it over the weekend.

**Comment by BrockReece** [comment]
@Shinigami92 Sorry for the wait, would you mind checking the change in https://github.com/BrockReece/vue-heatmapjs/pull/23? I think that would solve this.

**Comment by Shinigami92** [comment]
You can use `npm publish —dry-run` to see all served files

**Comment by Shinigami92** [comment]
Files like License, Readme or Changelog could also be served

**Comment by BrockReece** [comment]
Those files are automatically included when using an `.npmignore` blacklist or `files` based whitelist.

Running `npm pack` locally creates a tarball file that I could unpack and inspect. It all looks good to me, so I have published a preminor release for testing: `v1.5.0-0`

**Comment by Shinigami92** [comment]
Much cleaner now 👍 

![image](https://user-images.githubusercontent.com/7195563/74665829-b4e8e300-51a0-11ea-8a8e-79294e7cc40d.png)

**Comment by BrockReece** [comment]
Nice, I guessing it hasn't broken anything either?
If not I will get this merged down and tagged up properly.

Thanks for your help.
